<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <RootNamespace>MarkItDownApp</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platform Condition="'$(Platform)' == '' or '$(Platform)' == 'AnyCPU'">x64</Platform>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WindowsSdkPackageVersion>10.0.26100.81</WindowsSdkPackageVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.250907003" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4654" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3179.45" />
    <PackageReference Include="Microsoft.WSL.Containers" Version="2.8.7-build4" />
  </ItemGroup>

  <ItemGroup Condition="Exists('Container\markitdown.tar')">
    <Content Include="Container\markitdown.tar" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <WslcImage Include="markitdown"
               Image="markitdown:latest"
               Dockerfile="Container\Containerfile"
               Context="Container"
               Sources="Container"
               TarLocation="$(OutDir)\Container\markitdown.tar" />
  </ItemGroup>

</Project>
